name: Email Reminder Scheduler

# Futtatás ütemezve: minden nap 08:00-kor (UTC szerint)
on:
  schedule:
    - cron: "0 8 * * *"
  # Manuális futtatás is lehetséges
  workflow_dispatch:

jobs:
  emailReminder:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run email reminder script
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_SECURE: ${{ secrets.SMTP_SECURE }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: npm run emailreminder