name: Email Reminder Scheduler

on:
  workflow_dispatch:      # Ez engedélyezi a manuális indítást
  schedule:
    - cron: "42 10 * * *" # Ez azt jelenti, hogy UTC szerint 13:35-kor fut – ez GMT+2 esetén 15:35 helyi idő

jobs:
  emailReminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run email reminder script
        run: npm run emailreminder
