name: Email Reminder Scheduler

on:
  workflow_dispatch: {}  # Manuális indítás engedélyezése
  schedule:
    - cron: "45 10 * * *"  # 10:45 UTC = 12:45 CEST

jobs:
  emailReminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run email reminder script
        run: npm run emailreminder
